version: '3.9'

services:
  video-upload-client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: video_upload_client
    volumes:
      - ./:/home/node/video_upload_client
    ports:
      - 3000:3000

networks: 
  default:
    name: video_upload_network
    external: true