FROM golang:latest

RUN apt update && \
	apt full-upgrade -y

RUN apt install protobuf-compiler -y

RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28 && \
	go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2 && \
	go install github.com/ktr0731/evans@latest

WORKDIR /home/video_upload_server

COPY . .

RUN go mod tidy

CMD ["tail", "-f", "/dev/null"]
